version: "3"
services:

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
        - "8080:8080"
#    volumes:
#      - .:/app
    network_mode: "host"
    environment:
      EV_PORT: ${EV_PORT}
      PATH: "mongodb://docker:docker@0.0.0.0:27017"
      DB_USER: ${EV_DB_USER}
      DB_PASS: ${EV_DB_PASS}
      DB_NAME: ${EV_DB_NAME}
    command: ./app
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db-data:/var/lib/mongodb/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker
    restart: always

volumes:
  db-data: