version: "3"
services:

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: "host"
    environment:
      PATH: ${EV_DB_PATH}
      DB_USER: ${EV_DB_USER}
      DB_PASS: ${EV_DB_PASS}
      DB_NAME: ${EV_DB_NAME}
    command: ./app
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db-data:/var/lib/mongodb/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${EV_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${EV_DB_PASS}
    restart: always

volumes:
  db-data: