definitions:
  models.User:
    properties:
      birthday:
        type: string
      ctime:
        type: integer
      dtime:
        type: integer
      email:
        type: string
      first_name:
        type: string
      fullname:
        type: string
      id:
        type: string
      last_name:
        type: string
      mtime:
        type: integer
      password:
        type: string
      phone:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is DJM api docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: DJM API
  version: "1.0"
paths:
  /api/v1/users:
    post:
      consumes:
      - application/json
      description: Create user
      operationId: user-create
      parameters:
      - description: user id
        in: header
        name: x-user-id
        type: string
      - description: user data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Create user
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
